### ISSUE TITLE
App gives false information for devices made after 2020

### ISSUE THREAD

**Issue by hero3210** [aydenp/Serial#2]
At the end of 2019 the serials reached ZY
& the new iPhones that were made in 2020 had serials beginning with C1 and now they reached D8 I believe. 

If you can update the app to apply this change I’ll be very grateful. 

Currently, Serial app correctly detects the device model but it shows iOS 13.0 as the probable version for all 2020 devices which is not correct (also the dates for the week are not correct as they are from 2010).

Thanks again for making this very useful tool.

**Comment by aydenp** [comment]
Serial has been succeeded by Reincubate Lookup, which you can read more about [here](https://reincubate.com/blog/serial-lookup-imei-checker-for-ios/). It features a brand-new design and tons more information.

[![Download on the App Store](https://reincubate.com/res/lookup/i/badges/app_store/app_store_en.svg)](https://apps.apple.com/app/reincubate-lookup/id1483923951)
