### ISSUE TITLE
Serial non work

### ISSUE THREAD

**Issue by salvatore8686** [aydenp/Serial#3]
Bro ipa is no longer showing the IOS version, I hope you have time and desire to update this magnificent application. Thanks

**Comment by aydenp** [comment]
Serial has been succeeded by Reincubate Lookup, which you can read more about [here](https://reincubate.com/blog/serial-lookup-imei-checker-for-ios/). It features a brand-new design and tons more information.

[![Download on the App Store](https://reincubate.com/res/lookup/i/badges/app_store/app_store_en.svg)](https://apps.apple.com/app/reincubate-lookup/id1483923951)
